name: UI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov  # Добавляем эту строку
          playwright install --with-deps

      - name: Create .env
        run: |
          echo "APP_URL=https://nikita-filonov.github.io/qa-automation-engineer-ui-course" > .env
          echo "HEADLESS=true" >> .env
          echo 'BROWSERS=["webkit","chromium","firefox"]' >> .env
          echo "TEST_USER_EMAIL=user.name@gmail.com" >> .env
          echo "TEST_USER_USERNAME=username" >> .env
          echo "TEST_USER_PASSWORD=password" >> .env
          echo "TEST_DATA_IMAGE_PNG_FILE=./testdata/files/image.png" >> .env

      - name: Run tests
        run: |
          pytest -m regression \
            --alluredir=allure-results \
            --numprocesses 2 \
            --cov=. \
            --cov-report=json:coverage.json

      - name: Restore coverage history
        uses: actions/cache/restore@v4
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}
          restore-keys: coverage-history-

      - name: Generate report
        run: ui-coverage-tool save-report

      - name: Save coverage history
        if: always()
        uses: actions/cache/save@v4
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Upload allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results